CREATE TABLE brand (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    brand_id BIGINT NOT NULL,
    description VARCHAR(255),
    CONSTRAINT fk_product_brand FOREIGN KEY (brand_id) REFERENCES brand(id)
);

CREATE TABLE product_price (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    price_list_id BIGINT NOT NULL,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    rank BIGINT NOT NULL,
    amount VARCHAR(255) NOT NULL,
    currency VARCHAR(10) NOT NULL,
    CONSTRAINT fk_product_price_product FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE INDEX ON product_price(product_id, start_date, end_date, rank);
COMMENT ON COLUMN product_price.rank IS 'number that unties results in case of multiple matches'