name: Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build and test with Gradle
      run: ./gradlew test --parallel
      
    - name: Run coverage verification
      run: ./gradlew jacocoTestCoverageVerification
    
    - name: Upload test & coverage reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-and-coverage-reports
        path: build/reports/

    - name: Publish coverage report
      uses: coverallsapp/github-action@v2
      with:
        file: build/reports/jacoco/test/jacocoTestReport.xml