name: Build and test

on: push

 # https://github.com/marketplace/actions/junit-report-action#pr-run-permissions
permissions:
  checks: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: coursier-cache-action
      uses: coursier/cache-action@6.4.7

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build and test with Mill
      run: ./mill test

#    - name: Run coverage verification
#      run: ./gradlew jacocoTestCoverageVerification

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v5
      if: always()
      with:
        fail_on_failure: false
        include_passed: false
        detailed_summary: true
        annotate_only: true
        require_tests: false
        report_paths: 'out/**/test-report.xml'

#    - name: Publish coverage report
#      uses: coverallsapp/github-action@v2
#      with:
#        file: build/reports/jacoco/test/jacocoTestReport.xml